services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
